ui:
  active_theme: princess

generations:
  most_recent: 9
  min_supported: 3

paths:
  themes: themes/
  basestats: data/basestats.csv
  characteristics: data/characteristics.csv
  natures: data/natures.csv
  statchanges: data/statchanges.csv
  icons:
    main: assets/icon.png
    warning: assets/warning.png