ui:
  # relief should be one of
  # flat, raised, sunken, groove, ridge
  textbox_relief: flat

generations:
  most_recent: 9
  min_supported: 3

paths:
  basestats: data/basestats.csv
  characteristics: data/characteristics.csv
  natures: data/natures.csv
  statchanges: data/statchanges.csv
  icon: assets/icon.png